version: '2'

services:

### Workspace Utilities Container ###########################

    workspace:
        build:
            context: ./docker/workspace
            args:
                - PUID=1000
                - PGID=1000
                - TZ=EUROPE/PARIS
        volumes_from:
            - volumes_source
        ports:
           - "2222:22"
        tty: true

### PHP-FPM Container #######################################

    php-fpm:
        build:
            context: ./docker/php-fpm
            dockerfile: Dockerfile-56
        volumes_from:
            - volumes_source
        expose:
            - "9000"
        links:
            - workspace

### Nginx Server Container ##################################

    nginx:
        build:
            context: ./docker/nginx
            args:
                - PHP_UPSTREAM=php-fpm
        volumes_from:
            - volumes_source
        volumes:
            - ./docker/logs/nginx/:/var/log/nginx
        ports:
            - "80:80"
            - "443:443"
        links:
            - php-fpm

### Apache Server Container ##################################

    apache2:
        build:
            context: ./docker/apache2
            args:
                - PHP_SOCKET=php-fpm:9000
        volumes_from:
            - volumes_source
        volumes:
            - ./docker/logs/apache2:/var/log/apache2
        ports:
            - "80:80"
            - "443:443"
        links:
            - php-fpm

### MySQL Container #########################################

    mysql:
        build: ./docker/mysql
        volumes_from:
            - volumes_data
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root

### Laravel Application Code Container ######################

    volumes_source:
        image: tianon/true
        volumes:
            - ./:/var/www/symfony

### Databases Data Container ################################

    volumes_data:
        image: tianon/true
        volumes:
            - ./docker/data/mysql:/var/lib/mysql
            - ./docker/data/sessions:/sessions
